CRITICAL - 2023-10-31 09:35:50 --> file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'file_get_conten...', 'D:\\xampp\\htdocs...', 8, Array)
#1 D:\xampp\htdocs\peluit\app\Helpers\notification_helper.php(8): file_get_contents('https://api.tel...')
#2 D:\xampp\htdocs\peluit\app\Controllers\Auth.php(281): telegram('6155320137', 'Silahkan gunaka...')
#3 D:\xampp\htdocs\peluit\system\CodeIgniter.php(824): App\Controllers\Auth->send_otp()
#4 D:\xampp\htdocs\peluit\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#5 D:\xampp\htdocs\peluit\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 D:\xampp\htdocs\peluit\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2023-10-31 09:44:49 --> file_get_contents(https://api.telegram.org/bot6315272274:AAHOrEVzKuxP7Cz_5y21YvKR8SNPQavAW34/sendMessage?chat_id=6155320137&amp;text=Haloo+Admin.%0D%0A++++++++++++++++%0A%0AAyo+login%2C+ada+permohonan+pembuatan+akun+yang+harus+kamu+verifikasi.+%0A%0ANama+%3A+Marlena%0A%0ACivitas+%3A+SMKN+02+BANGKALN): failed to open stream: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'file_get_conten...', 'D:\\xampp\\htdocs...', 8, Array)
#1 D:\xampp\htdocs\peluit\app\Helpers\notification_helper.php(8): file_get_contents('https://api.tel...')
#2 D:\xampp\htdocs\peluit\app\Controllers\Auth.php(229): telegram('6155320137', 'Haloo Admin.\r\n ...')
#3 D:\xampp\htdocs\peluit\system\CodeIgniter.php(824): App\Controllers\Auth->register()
#4 D:\xampp\htdocs\peluit\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#5 D:\xampp\htdocs\peluit\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 D:\xampp\htdocs\peluit\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
ERROR - 2023-10-31 12:02:54 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;ssuser.id_ssuser&quot; must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: SELECT &quot;ssuser&quot;.&quot;id_ssuser&quot;, &quot;ssuser&quot;.&quot;username&quot;
               ^ in D:\xampp\htdocs\peluit\system\Database\Postgre\Connection.php:136
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'D:\\xampp\\htdocs...', 136, Array)
#1 D:\xampp\htdocs\peluit\system\Database\Postgre\Connection.php(136): pg_query(Resource id #126, 'SELECT "ssuser"...')
#2 D:\xampp\htdocs\peluit\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "ssuser"...')
#3 D:\xampp\htdocs\peluit\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "ssuser"...')
#4 D:\xampp\htdocs\peluit\system\Database\BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT "ssuser"...', Array, false)
#5 D:\xampp\htdocs\peluit\app\Controllers\Form.php(987): CodeIgniter\Database\BaseBuilder->get()
#6 D:\xampp\htdocs\peluit\system\CodeIgniter.php(824): App\Controllers\Form->get_opd_operator()
#7 D:\xampp\htdocs\peluit\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Form))
#8 D:\xampp\htdocs\peluit\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\peluit\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-10-31 12:02:54 --> pg_query(): Query failed: ERROR:  column &quot;ssuser.id_ssuser&quot; must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: SELECT &quot;ssuser&quot;.&quot;id_ssuser&quot;, &quot;ssuser&quot;.&quot;username&quot;
               ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'D:\\xampp\\htdocs...', 136, Array)
#1 D:\xampp\htdocs\peluit\system\Database\Postgre\Connection.php(136): pg_query(Resource id #126, 'SELECT "ssuser"...')
#2 D:\xampp\htdocs\peluit\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "ssuser"...')
#3 D:\xampp\htdocs\peluit\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "ssuser"...')
#4 D:\xampp\htdocs\peluit\system\Database\BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT "ssuser"...', Array, false)
#5 D:\xampp\htdocs\peluit\app\Controllers\Form.php(987): CodeIgniter\Database\BaseBuilder->get()
#6 D:\xampp\htdocs\peluit\system\CodeIgniter.php(824): App\Controllers\Form->get_opd_operator()
#7 D:\xampp\htdocs\peluit\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Form))
#8 D:\xampp\htdocs\peluit\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\peluit\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-10-31 12:02:54 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in D:\xampp\htdocs\peluit\system\Format\JSONFormatter.php:41
Stack trace:
#0 D:\xampp\htdocs\peluit\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 D:\xampp\htdocs\peluit\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 D:\xampp\htdocs\peluit\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 D:\xampp\htdocs\peluit\system\Debug\Exceptions.php(110): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2023-10-31 12:04:22 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;ssopd.nama_opd&quot; must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: SELECT &quot;ssuser&quot;.&quot;id_opd&quot;, &quot;ssopd&quot;.&quot;nama_opd&quot;
                                  ^ in D:\xampp\htdocs\peluit\system\Database\Postgre\Connection.php:136
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'D:\\xampp\\htdocs...', 136, Array)
#1 D:\xampp\htdocs\peluit\system\Database\Postgre\Connection.php(136): pg_query(Resource id #126, 'SELECT "ssuser"...')
#2 D:\xampp\htdocs\peluit\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "ssuser"...')
#3 D:\xampp\htdocs\peluit\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "ssuser"...')
#4 D:\xampp\htdocs\peluit\system\Database\BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT "ssuser"...', Array, false)
#5 D:\xampp\htdocs\peluit\app\Controllers\Form.php(987): CodeIgniter\Database\BaseBuilder->get()
#6 D:\xampp\htdocs\peluit\system\CodeIgniter.php(824): App\Controllers\Form->get_opd_operator()
#7 D:\xampp\htdocs\peluit\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Form))
#8 D:\xampp\htdocs\peluit\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\peluit\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-10-31 12:04:22 --> pg_query(): Query failed: ERROR:  column &quot;ssopd.nama_opd&quot; must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: SELECT &quot;ssuser&quot;.&quot;id_opd&quot;, &quot;ssopd&quot;.&quot;nama_opd&quot;
                                  ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'D:\\xampp\\htdocs...', 136, Array)
#1 D:\xampp\htdocs\peluit\system\Database\Postgre\Connection.php(136): pg_query(Resource id #126, 'SELECT "ssuser"...')
#2 D:\xampp\htdocs\peluit\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "ssuser"...')
#3 D:\xampp\htdocs\peluit\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "ssuser"...')
#4 D:\xampp\htdocs\peluit\system\Database\BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT "ssuser"...', Array, false)
#5 D:\xampp\htdocs\peluit\app\Controllers\Form.php(987): CodeIgniter\Database\BaseBuilder->get()
#6 D:\xampp\htdocs\peluit\system\CodeIgniter.php(824): App\Controllers\Form->get_opd_operator()
#7 D:\xampp\htdocs\peluit\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Form))
#8 D:\xampp\htdocs\peluit\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\peluit\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-10-31 12:04:22 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in D:\xampp\htdocs\peluit\system\Format\JSONFormatter.php:41
Stack trace:
#0 D:\xampp\htdocs\peluit\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 D:\xampp\htdocs\peluit\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 D:\xampp\htdocs\peluit\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 D:\xampp\htdocs\peluit\system\Debug\Exceptions.php(110): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2023-10-31 12:04:56 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;ssuser.username&quot; must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: SELECT &quot;ssuser&quot;.&quot;id_opd&quot;, &quot;ssuser&quot;.&quot;username&quot;
                                  ^ in D:\xampp\htdocs\peluit\system\Database\Postgre\Connection.php:136
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'D:\\xampp\\htdocs...', 136, Array)
#1 D:\xampp\htdocs\peluit\system\Database\Postgre\Connection.php(136): pg_query(Resource id #126, 'SELECT "ssuser"...')
#2 D:\xampp\htdocs\peluit\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "ssuser"...')
#3 D:\xampp\htdocs\peluit\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "ssuser"...')
#4 D:\xampp\htdocs\peluit\system\Database\BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT "ssuser"...', Array, false)
#5 D:\xampp\htdocs\peluit\app\Controllers\Form.php(987): CodeIgniter\Database\BaseBuilder->get()
#6 D:\xampp\htdocs\peluit\system\CodeIgniter.php(824): App\Controllers\Form->get_opd_operator()
#7 D:\xampp\htdocs\peluit\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Form))
#8 D:\xampp\htdocs\peluit\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\peluit\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-10-31 12:04:56 --> pg_query(): Query failed: ERROR:  column &quot;ssuser.username&quot; must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: SELECT &quot;ssuser&quot;.&quot;id_opd&quot;, &quot;ssuser&quot;.&quot;username&quot;
                                  ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'D:\\xampp\\htdocs...', 136, Array)
#1 D:\xampp\htdocs\peluit\system\Database\Postgre\Connection.php(136): pg_query(Resource id #126, 'SELECT "ssuser"...')
#2 D:\xampp\htdocs\peluit\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT "ssuser"...')
#3 D:\xampp\htdocs\peluit\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT "ssuser"...')
#4 D:\xampp\htdocs\peluit\system\Database\BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT "ssuser"...', Array, false)
#5 D:\xampp\htdocs\peluit\app\Controllers\Form.php(987): CodeIgniter\Database\BaseBuilder->get()
#6 D:\xampp\htdocs\peluit\system\CodeIgniter.php(824): App\Controllers\Form->get_opd_operator()
#7 D:\xampp\htdocs\peluit\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Form))
#8 D:\xampp\htdocs\peluit\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\peluit\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-10-31 12:04:56 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in D:\xampp\htdocs\peluit\system\Format\JSONFormatter.php:41
Stack trace:
#0 D:\xampp\htdocs\peluit\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 D:\xampp\htdocs\peluit\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 D:\xampp\htdocs\peluit\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 D:\xampp\htdocs\peluit\system\Debug\Exceptions.php(110): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
