ERROR - 2023-07-27 13:23:32 --> ErrorException: pg_query(): Query failed: ERROR:  null value in column &quot;id_opd&quot; violates not-null constraint
DETAIL:  Failing row contains (6, null, null, null, null, logokominfo.png, 1, 2023-06-15 10:47:34.617498, null). in D:\xampp\htdocs\peluit\system\Database\Postgre\Connection.php:136
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'D:\\xampp\\htdocs...', 136, Array)
#1 D:\xampp\htdocs\peluit\system\Database\Postgre\Connection.php(136): pg_query(Resource id #131, 'UPDATE "sspelay...')
#2 D:\xampp\htdocs\peluit\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('UPDATE "sspelay...')
#3 D:\xampp\htdocs\peluit\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE "sspelay...')
#4 D:\xampp\htdocs\peluit\system\Database\BaseBuilder.php(1901): CodeIgniter\Database\BaseConnection->query('UPDATE "sspelay...', Array, false)
#5 D:\xampp\htdocs\peluit\system\Model.php(298): CodeIgniter\Database\BaseBuilder->update()
#6 D:\xampp\htdocs\peluit\system\BaseModel.php(865): CodeIgniter\Model->doUpdate(NULL, Array)
#7 D:\xampp\htdocs\peluit\system\Model.php(646): CodeIgniter\BaseModel->update(NULL, Array)
#8 D:\xampp\htdocs\peluit\app\Controllers\Admin.php(959): CodeIgniter\Model->update(NULL, Array)
#9 D:\xampp\htdocs\peluit\system\CodeIgniter.php(824): App\Controllers\Admin->update_faq()
#10 D:\xampp\htdocs\peluit\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#11 D:\xampp\htdocs\peluit\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\xampp\htdocs\peluit\index.php(37): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2023-07-27 13:23:32 --> pg_query(): Query failed: ERROR:  null value in column &quot;id_opd&quot; violates not-null constraint
DETAIL:  Failing row contains (6, null, null, null, null, logokominfo.png, 1, 2023-06-15 10:47:34.617498, null).
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'D:\\xampp\\htdocs...', 136, Array)
#1 D:\xampp\htdocs\peluit\system\Database\Postgre\Connection.php(136): pg_query(Resource id #131, 'UPDATE "sspelay...')
#2 D:\xampp\htdocs\peluit\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('UPDATE "sspelay...')
#3 D:\xampp\htdocs\peluit\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE "sspelay...')
#4 D:\xampp\htdocs\peluit\system\Database\BaseBuilder.php(1901): CodeIgniter\Database\BaseConnection->query('UPDATE "sspelay...', Array, false)
#5 D:\xampp\htdocs\peluit\system\Model.php(298): CodeIgniter\Database\BaseBuilder->update()
#6 D:\xampp\htdocs\peluit\system\BaseModel.php(865): CodeIgniter\Model->doUpdate(NULL, Array)
#7 D:\xampp\htdocs\peluit\system\Model.php(646): CodeIgniter\BaseModel->update(NULL, Array)
#8 D:\xampp\htdocs\peluit\app\Controllers\Admin.php(959): CodeIgniter\Model->update(NULL, Array)
#9 D:\xampp\htdocs\peluit\system\CodeIgniter.php(824): App\Controllers\Admin->update_faq()
#10 D:\xampp\htdocs\peluit\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#11 D:\xampp\htdocs\peluit\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\xampp\htdocs\peluit\index.php(37): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2023-07-27 13:23:32 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in D:\xampp\htdocs\peluit\system\Format\JSONFormatter.php:41
Stack trace:
#0 D:\xampp\htdocs\peluit\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 D:\xampp\htdocs\peluit\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 D:\xampp\htdocs\peluit\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 D:\xampp\htdocs\peluit\system\Debug\Exceptions.php(110): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
